### ISSUE TITLE
add registerBuildPlugin

### ISSUE THREAD

**Issue by aaronjudd** [timothyarmes/packagecheck#1]
Great idea. very useful. 

`Package.registerBuildPlugin` in the package's `packages.js` causes exit with `TypeError: undefined is not a function`.

Looks like you just need to add to https://github.com/timothyarmes/packagecheck/blob/ccebff73a6da54b6b1d51d0962c92939d55ae507/package.js#L64

**Comment by timothyarmes** [comment]
Thanks, I've fixed that now.

**Comment by aaronjudd** [comment]
looks good! I'd suggest you add the deprecated syntax of `on_use`, `on_addFiles`, etc as well - as these also break the script.  Personally - I think it would be cool - since you are going thru them anyways to spit out a warning "Using deprecated : `on_use` in package xxx".

**Comment by timothyarmes** [comment]
Those should already be handled by the latest release.  Let me know if I've missed any.
Good idea for the message :)

**Comment by ssteinerx** [comment]
@aaronjudd I agree, very good idea for the message as my use of one of those deprecated functions was one of the issues I ran into earlier.  Is there a way to get Meteor to warn about that, or are we working on the thing that will ;-).

**Comment by aaronjudd** [comment]
In the meteor code it's pretty much just an alias, I don't think there is anything to warn you that you are using some deprecated format (and that would be really annoying if it was someone else's package) -  but since this tool is a place to check the "package" dependencies - hey why not use it to make sure the package declaration is up to date as well.

**Comment by timothyarmes** [comment]
I've added deprecation checks to the latest release (use the --warn option).
