### ISSUE TITLE
Doesn't accept local package dependencies without version numbers

### ISSUE THREAD

**Issue by stubailo** [timothyarmes/packagecheck#10]
```
=> Checking package less-globals...
{ [Error: Version string must look like semver (eg '1.2.3'), not 'local'.] versionParserError: true }
```

This is from this package.js:

https://github.com/meteor/todos/blob/1caba6e5f9ad9645b8ef7cf7c3c7c0dea150ec60/packages/less-globals/package.js#L7

**Comment by timothyarmes** [comment]
I've just used a fix for this.

Sorry for the very late response, I hadn't seen the issue come through on my email.
