### ISSUE TITLE
Crash when run in Meteor project directory

### ISSUE THREAD

**Issue by ssteinerx** [timothyarmes/packagecheck#3]
Users/ssteiner/Desktop/meteor/val-dashboard/packages/npm-container/package.js:10
var packagesJsonFile = path.resolve('./packages.json');
                           ^
TypeError: Cannot read property 'resolve' of undefined
    at Object.<anonymous> (/Users/ssteiner/Desktop/meteor/val-dashboard/packages/npm-container/package.js:10:28)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /usr/local/lib/node_modules/packagecheck/index.js:61:11
    at Array.filter (native)
    at scanPackages (/usr/local/lib/node_modules/packagecheck/index.js:55:30

**Comment by timothyarmes** [comment]
Is this failing on one specific package. If so, can you attach the package.js file for that package?

**Comment by ssteinerx** [comment]
It's failing in the root of a Meteor project right away.

S

**Comment by timothyarmes** [comment]
Does it also fail if run from the packages folder?

**Comment by ssteinerx** [comment]
Same way.  It's saying that `path` is undefined.

It appears to be importing npm-container/package.js which is not even part of your code...a fishy import statement?

```
Users/ssteiner/xxxxxxx/packages/npm-container/package.js:10
var packagesJsonFile = path.resolve('./packages.json');
                           ^
TypeError: Cannot read property 'resolve' of undefined
```

**Comment by ssteinerx** [comment]
This project uses meteorhacks:npm and there is no packages.json in the root directory.

**Comment by ssteinerx** [comment]
Actually, packages.json is this:

```
{
  "debug": "2.2.0",
  "cheerio": "0.19.0",
  "lodash": "3.9.3",
  "fast-csv": "0.6.0",
  "js2xmlparser": "0.1.9",
  "request": "2.60.0",
  "csvtojson": "0.4.1"
}
```

It is used by meteorhacks:npm to control which node modules are made available in a "Meteorish" way.

**Comment by ssteinerx** [comment]
This looks like an unfortunate case of conflicting file naming.  The package.js file in a package is supposed to be the one that determines where files in the package go at runtime etc. but your package is looking for package.json which is used by meteorhacks:npm to determine which node packages to load.

And, you've got a file named package.js in this package which mucks things up even more.

**Comment by timothyarmes** [comment]
Actually the problem was more subtly than that (I never ready the .json files), however you were right to point out that the meteorhacks:npm package was provoking the bug. I've just pushed 0.1.6 to fix it.
