### ISSUE TITLE
New crash, gets a little further, crashes on *my* typo...

### ISSUE THREAD

**Issue by ssteinerx** [timothyarmes/packagecheck#4]
The ssteinerX:cart-exporter is a symlink to a collection of meteor packages elsewhere on my system.

This particular crash is triggered by a typo in my package.js where it said on_test instead of onTest.

Correcting the typo fixes the crash; I'll leave it up to you whether this is worth fixing.  

After fixing the typo, I get this:

```
Checking package npm-container...
Checking package ssteinerx:cart-exporter...
```

Not too informative; leaves me wondering whether anything happened... --verbose, please?

```
# packagecheck
Checking package npm-container...
Checking package ssteinerx:cart-exporter...
/Users/ssteiner/Desktop/meteor/wssw-meteor-packages/ssteinerx_cart-exporter/package.js:39
Package.on_test(function (api) {
        ^
TypeError: undefined is not a function
    at Object.<anonymous> (/...my-meteor-packages/ssteinerx_cart-exporter/package.js:39:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /usr/local/lib/node_modules/packagecheck/index.js:61:11
    at Array.filter (native)
    at scanPackages (/usr/local/lib/node_modules/packagecheck/index.js:55:30)
```

**Comment by timothyarmes** [comment]
Actually, `on_test` and `on_use` are the deprecated versions of `onTest`and `onUse`, so I've added support for them.

I've also added a --verbose option.

Both changes have been pushed out in version 0.1.7.

**Comment by ssteinerx** [comment]
Super!  Works and is kind of verbose.  I'd add an "You are using version..." to the "does not have a version constraint" message.  I'm looking to this tool to show me a little more about what I'm using...so I can decide whether to, for example, pull a repository for a bug fix I might be needing.

**Comment by ssteinerx** [comment]
Also, I want my "most active bug reporter" sticker now, please ;-).

**Comment by timothyarmes** [comment]
Good idea. The latest version now checks to  see if the version actually used by a project of an unconstrained dependency is up to date.

You can also be warned of all uses of unconstrained dependendencies (up-to-date or otherwise) using either the --unconstrained or --verbose options.
