### ISSUE TITLE
Requires `README` or `documentation: null` to run

### ISSUE THREAD

**Issue by stubailo** [timothyarmes/packagecheck#9]
I get a bunch of these errors when I run the tool: 

```
=> Errors while reading local packages:

While reading /Users/sashko/git/todos/packages/less-globals:
error: Documentation not found: README.md
If you don't want to publish any documentation, please set 'documentation:
null' in Package.describe



=> Checking package todos-auth...
=> Errors while reading local packages:

While reading /Users/sashko/git/todos/packages/todos-lib:
error: Documentation not found: README.md
If you don't want to publish any documentation, please set 'documentation:
null' in Package.describe
```

I've intentionally removed the documentation section since these packages will never be published. I could add `documentation: null`, but it seems unfortunate that the package works fine in my app but not with `packagecheck`.

**Comment by timothyarmes** [comment]
I can't fix this I'm afraid. PackageCheck uses Meteor itself to do the hard work; I run `meteor show` on the packages and extract the information required. That error comes from that command.
